project:
  type: website
  output-dir: docs


website:
  title: "Sample Tutorials"
  sidebar:
    style: "docked"
    contents:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true